#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan  2 13:59:16 2018

@author: Mark
"""

import random 
for i in range (1,10,2):
    print ('this is the ' + str(i) + ' of number: ')
    print (random.randint(1,10))
    